parameters:
    
    
services:
    buzz:
        class: Buzz\Browser
    yammer:
        class: ZENben\Bundle\YammerBundle\Service\YammerService
        arguments:
            - '@buzz'
            - %yammer%